--- 
- hosts: localhost
  become: true
  gather_facts: Yes


  tasks :   
    - name: Install basic packages for ansible
      apt: name={{ item }}
          state=latest
      with_items: 
        - python3-pip
        - python3-setuptools
      tags: [ packages ]

    - name: Install ansible
      pip:
        name: ansible
        executable: /usr/bin/pip3