---
    - name: Run a shell command and register its output as a variable
      ansible.builtin.shell: "uname -r "
      register: os_version
      ignore_errors: true


    - name: install default SO headers
      shell: |
        """apt-get install linux-headers-{{os_version['stdout_lines'][0]}}"""
      ignore_errors: yes




    - name: Install basic packages
      apt: name={{ item }}
          state=latest
      with_items: "{{ packages}}"
      tags: [ packages ]



    - name: reinstall libc6
      shell: |
        apt-get install --reinstall libc6-i386
      tags: [ packages ]

    - name: Install teams
      apt:
        name: teams
        state: present   
      tags: [ packages ]       

    - name: Install Joplin, a taking notes app
      shell: |
        wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash        
      tags: [ packages ]

