---
    - name: Creates VPN cronjob
      ignore_errors: yes
      cron:
        name: Connect VPN
        user: root
        minute: "*"
        hour:   "1-21"
        weekday: "1-7"
        job:  "/bin/bash /root/vpn.sh 2>&1 >> /var/log/vpn.log" 
      tags:
        - crons

    - name: Creates shutdown cronjob
      ignore_errors: yes
      cron:
        name: Shutdown.
        user: root
        minute: "40"
        hour:   "23,00"
        weekday: "1-7"
        job:  "shutdown  now" 
      tags:
        - crons