---
    - name: create directories
      file:
        path: "/home/{{USER}}/git"
        state: directory
        owner: "{{USER}}"
        group: "{{USER}}"

    - name: Add the user 
      ansible.builtin.user:
        shell: /bin/bash
        name: "{{USER}}"
        append: yes
        
    - name: Add {{USER}} user to sudoers
      shell: |
        echo "{{USER}}     ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/{{USER}}

    - name: Customize bashrc
      blockinfile:
        dest: "/home/{{USER}}/.bashrc"
        block: |
          alias ll='ls -latr'
          if [ $TILIX_ID ] || [ $VTE_VERSION ]; then 
                  source /etc/profile.d/vte-2.91.sh  
          fi
          export EDITOR=vim 
          export PATH=$PATH:$HOME 
          export HISTSIZE=10000                 
          alias conf='ssh -t  -l epg  prod-epg-conf-01 n  " sudo /bin/bash"'
          alias ir='      ssh -l epg'
          alias ci='      ssh -t  -l epg ci-epg-vmwar-01    " sudo /bin/bash"'
          alias grafana=' ssh -t  -l epg grafana            " sudo /bin/bash"'
          alias ici='     ssh -t  -l epg prod-epg-icimas-01 " sudo /bin/bash"'
          alias jira='    ssh -t  -l epg prod-epg-jira-01   " sudo /bin/bash"'
          alias vcop='    ssh -t  -l epg pro-dcip-vcop-01   " sudo /bin/bash"'
          #alias inv=" cd /home/jaimevalero/git/epg-airflow/ ;  conda activate epg-airflow ; make  restart"
          alias inv=" cd /home/jaimevalero/git/epg-airflow/ ;  conda activate epg-airflow ;docker-compose -f docker-compose.dev.yaml up -d"
          alias build=" cd /home/jaimevalero/git/epg-airflow/ ;  conda activate epg-airflow ; docker-compose -f docker-compose.dev.yaml build"
          alias h='function hdi(){ howdoi $* -c -n 5; }; hdi'
        marker: '# {mark} ANSIBLE MANAGED BLOCK '
        insertbefore: BOF
        create: yes 
