---
    - name: Play needed tasks in order
      include_tasks: "{{ item }}"
      loop:
        - basic_installation.yml
        - customizations.yml
        - crons.yml
        - frontend.yml
        - backend.yml
        - docker.yml
        - network_drivers.yml
      
